coverage:
    status:
        project:
            default:
                # basic
                target: auto
                threshold: 90%
                base: auto
                flags:
                    - unit
                paths:
                    - 'src'
                # advanced
                if_not_found: success
                if_ci_failed: error
                informational: false
                only_pulls: false
